#!/usr/bin/env bash

SCRIPT_NAME="kindle-rsync"

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR="${DIR}/logs/${SCRIPT_NAME}"
mkdir -p ${LOGDIR}

LOGDATE=$(date '+%Y-%m-%d_%H-%M-%S')
LOGNAME="log_${SCRIPT_NAME}__${LOGDATE}.txt"
LOGFILE="${LOGDIR}/${LOGNAME}"


KINDLE_ADDR="alexialan"
LOCAL_PATH="/home/joaopizani/Text/portable/"
REM_PATH="${KINDLE_ADDR}:/mnt/us/DK_Documents"

rsync \
    --archive --no-owner --no-group --copy-links \
    --size-only --delete --progress \
    --exclude='*.dir*' --exclude='*fuse_hidden*'  \
    ${LOCAL_PATH} ${REM_PATH}

