#!/usr/bin/env bash

SCRIPT_NAME="kindle-rsync"

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGDIR="${DIR}/logs/${SCRIPT_NAME}"
mkdir -p "${LOGDIR}"

LOGDATE=$(date '+%Y-%m-%d_%H-%M-%S')
LOGNAME="log_${SCRIPT_NAME}__${LOGDATE}.txt"
LOGFILE="${LOGDIR}/${LOGNAME}"


KINDLE_ADDR="alexialan"
LOCAL_PATH_DEFAULT="${HOME}/Text/portable/"
LOCAL_PATH=${1:-$LOCAL_PATH_DEFAULT}
REM_PATH="${KINDLE_ADDR}:/mnt/us/DK_Documents"

rsync \
    --archive --no-owner --no-group --copy-links \
    --size-only --delete --progress \
    --exclude='*.dir*' --exclude='*fuse_hidden*'  \
    --human-readable --log-file="${LOGFILE}" \
    "${LOCAL_PATH}"  "${REM_PATH}"

